# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DEMCrawler
                                 A QGIS plugin
 Masks out altitude or basins upstream or downstream from a starting point.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-06
        copyright            : (C) 2021 by Nicolas Specklin
        email                : n.specklin@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):
    from .demcrawler_plugin import DEMCrawlerPlugin
    return DEMCrawlerPlugin(iface)
